# PolyCrawler development convenience commands (PowerShell).
# Usage: .\scripts\dev.ps1 <command>
#
# Commands:
#   install    - Install the package in editable mode with dev dependencies
#   lint       - Run ruff linter
#   typecheck  - Run mypy type checker
#   test       - Run pytest (fast)
#   test-cov   - Run pytest with coverage report
#   migrate    - Run pending Alembic migrations
#   db-up      - Generate a new autogenerated migration (set $env:MSG first)
#   db-down    - Roll back the last migration
#   run        - Start the FastAPI dev server with hot reload

param([string]$Command)

$PYTHON = "python"
$ALEMBIC = "alembic"

switch ($Command) {
    "install"   { & $PYTHON -m pip install -e ".[dev]" }
    "lint"      { & $PYTHON -m ruff check src/ tests/ }
    "typecheck" { & $PYTHON -m mypy src/ }
    "test"      { & $PYTHON -m pytest -v }
    "test-cov"  { & $PYTHON -m pytest --cov=src/poly_crawler --cov-report=term-missing }
    "migrate"   { & $ALEMBIC upgrade head }
    "db-up"     { & $ALEMBIC revision --autogenerate -m $env:MSG }
    "db-down"   { & $ALEMBIC downgrade -1 }
    "run"       { & $PYTHON -m uvicorn poly_crawler.main:app --reload }
    default     { Write-Host "Unknown command: $Command"; exit 1 }
}
